### ISSUE TITLE
cannot import name 'SELECT2_TRANSLATIONS'

### ISSUE THREAD

**Issue by Ashedu** [Yuego/django-fias#105]
Django (1.10.8)
django-appconf (1.0.4)
django-fias (1.2.5)
django-select2 (7.4.2)

При выполнении python manage.py fiasinfo --db-version
Или иных комманд на python manage.py
выпадает ошибка

> Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/fias/models/__init__.py", line 6, in <module>
    from .normdoc import *
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/fias/models/normdoc.py", line 7, in <module>
    from fias.fields import UUIDField
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/fias/forms.py", line 9, in <module>
    from django_select2.forms import ModelSelect2Widget
  File "/var/www/django-fias/venv/lib/python3.5/site-packages/django_select2/forms.py", line 55, in <module>
    from django.contrib.admin.widgets import SELECT2_TRANSLATIONS
ImportError: cannot import name 'SELECT2_TRANSLATIONS'

**Comment by Ashedu** [comment]
django-fias нужно ставить с гита, не через pip.
