### ISSUE TITLE
Ошибка при установке под Windows

### ISSUE THREAD

**Issue by andrey-oparin** [Yuego/django-fias#33]
D:\Dev\src\npf>pip install django-fias
Downloading/unpacking django-fias
  Running setup.py (path:D:\Temp\pip_build_Andrey\django-fias\setup.py) egg_info for package django-fias
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "D:\Temp\pip_build_Andrey\django-fias\setup.py", line 30, in <module>
        long_description=open('README.rst').read(),
      File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 71: character maps to <undefined>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "D:\Temp\pip_build_Andrey\django-fias\setup.py", line 30, in <module>

    long_description=open('README.rst').read(),

  File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 71: character maps to <undefined>

----------------------------------------
Cleaning up...

**Comment by andrey-oparin** [comment]
fix: 
import codecs
long_description=codecs.open('README.rst', encoding='utf8').read()
