### ISSUE TITLE
Неактуальная версия django_select2 в зависимостях

### ISSUE THREAD

**Issue by jungornti** [Yuego/django-fias#42]
./manage.py runserver                                                                                   
                                                                      
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f715fdb41e0>
Traceback (most recent call last):
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 107, in inner_run
    autoreload.raise_last_exception()
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/utils/autoreload.py", line 252, in raise_last_exception
    six.reraise(*_exception)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/utils/autoreload.py", line 229, in wrapper
    fn(*args, **kwargs)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/tmp/django-fias/test_project/env/lib/python3.4/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/tmp/django-fias/test_project/env/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/tmp/django-fias/test_project/fias/models/__init__.py", line 6, in <module>
    from .normdoc import NormDoc
  File "/tmp/django-fias/test_project/fias/models/normdoc.py", line 6, in <module>
    from fias.fields import UUIDField
  File "/tmp/django-fias/test_project/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/tmp/django-fias/test_project/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/tmp/django-fias/test_project/fias/forms.py", line 6, in <module>
    from django_select2.fields import HeavyModelSelect2ChoiceField
ImportError: No module named 'django_select2.fields

Должна подходить версия 4.3.1.

**Comment by Yuego** [comment]
Исправлено: #40
Обновите репозиторий.
Скоро будет готова версия с поддержкой django_select2 5.3+ и django 1.7+ (ниже 1.7 не будет миграций. по крайней мере пока)
