### ISSUE TITLE
Дубли при импорте данных

### ISSUE THREAD

**Issue by Yuego** [Yuego/django-fias#47]
Пока что использование set и проверки actstatus несколько уменьшили вероятность появления дублей, но вряд ли полностью её исключили. Думаем дальше.

**Comment by Yuego** [comment]
Итак, сегодня, 02.12.2015. Базы сегодняшние. Загружал только sorcbase и addrobj:
fias_dbf.rar - 0:40:37.753426, без ошибок
fias_xml.rar - почти в самом конце импорта [вылетело](http://pastebin.com/h02SZSng)

**Comment by Yuego** [comment]
Итак, оно работает. Добавил больше счетчиков времени и дополнил вывод импортера подробностями:

```
$ python manage_ext_postgres.py fias --src auto --update --format=dbf
Version info updated at 2015-12-06 12:05:15.347203+00:00. Estimated time: 0:00:02.285417
Downloading:  |################################| 100/100. ETA: 769
Loading data v.221 started at 2015-12-06 13:06:11.105911+00:00
Table: socrbase. Loaded: 259 | Updated: 0 | Skipped:  1         Filename: SOCRBASE.DBF
Table: addrobj. Loaded: 1227966 | Updated: 0 | Skipped:  1466741        Filename: ADDROBJ.DBF
Data v.221 from 2015-12-01 loaded at 2015-12-06 13:30:57.470996+00:00
Estimated time: 1:25:44.409210. Download: 0:12:49.320308. Unpack: 0:48:06.314250. Import: 0:24:46.385134
```

В сегодняшнем DBF дублей не обнаружилось.

**Comment by canufeel** [comment]
```
60130_f3ca0639-5e2b-45e6-87ed-e6b45627a82c.XMLTraceback (most recent call last):
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/importer/commands.py", line 59, in load_complete_data
    st = Status.objects.get(table=tbl)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
fias.models.version.DoesNotExist: Status matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.IntegrityError: duplicate key value violates unique constraint "fias_house_pkey"
DETAIL:  Key (houseguid)=(2132ace1-afa8-4fca-9570-7d127b8f4cb6) already exists.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/management/commands/fias.py", line 108, in handle
    load_complete_data(path=src, data_format=fmt, truncate=truncate, limit=limit)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/importer/commands.py", line 72, in load_complete_data
    loader.load(tablelist=tablelist, table=table)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/importer/loader.py", line 72, in load
    self.do_load(tablelist=tablelist, table=table)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/importer/loader.py", line 88, in do_load
    self.create(table, objects)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/fias/importer/loader.py", line 65, in create
    table.model.objects.bulk_create(objects)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/query.py", line 447, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/pk/.Envs/eis/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.IntegrityError: duplicate key value violates unique constraint "fias_house_pkey"
DETAIL:  Key (houseguid)=(2132ace1-afa8-4fca-9570-7d127b8f4cb6) already exists.
```
при первичном импорте по команде `./manage.py fias --src auto --truncate --i-know-what-i-do`

**Comment by Yuego** [comment]
Дубли появлялись из-за DEL-таблиц. По логике вещей записи, содержащиеся в них, нужно не добавлять, а наоборот удалять из БД. Но это тема для отдельной дискусии...

**Comment by Yuego** [comment]
Думаю, что пофикшено в версии 1.1.0 (скоро опубликую релиз)
