### ISSUE TITLE
Проблема с установкой через pip

### ISSUE THREAD

**Issue by aklim007** [Yuego/django-fias#48]
pip install django-fias
Ставит версию 0.5.0
При попытке руками прописать 0.6.1 получаем:
```
Collecting django-fias==0.6.1
  1 location(s) to search for versions of django-fias:
  * https://pypi.python.org/simple/django-fias/
  Getting page https://pypi.python.org/simple/django-fias/
  Looking up "https://pypi.python.org/simple/django-fias/" in the cache
  Current age based on date: 52
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 52
  Analyzing links from page https://pypi.python.org/simple/django-fias/
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.3.1.tar.gz#md5=6718ee0140da451c62f504a694ac40f4 (from https://pypi.python.org/simple/django-fias/), version: 0.3.1
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.3.2.tar.gz#md5=357d4ae7a8179a98b085cbf3ea2ad8ce (from https://pypi.python.org/simple/django-fias/), version: 0.3.2
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.3.tar.gz#md5=c625ccf2f11352f8e210ef9c929dd915 (from https://pypi.python.org/simple/django-fias/), version: 0.3
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.4.0.tar.gz#md5=ef9f91214e90fb3fccdaad6e207c608e (from https://pypi.python.org/simple/django-fias/), version: 0.4.0
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.5.0.tar.gz#md5=cf1eff9a735829cd42cc001c8a1fbbeb (from https://pypi.python.org/simple/django-fias/), version: 0.5.0
    Found link https://pypi.python.org/packages/source/d/django-fias/django-fias-0.5.1.tar.gz#md5=e1282fa15222e4b9631ace919716cdd7 (from https://pypi.python.org/simple/django-fias/), version: 0.5.1
  Could not find a version that satisfies the requirement django-fias==0.6.1 (from versions: 0.3, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.5.1)
Cleaning up...
No matching distribution found for django-fias==0.6.1
Exception information:
Traceback (most recent call last):
  File "/home/its/venv/lib/python3.4/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/home/its/venv/lib/python3.4/site-packages/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/home/its/venv/lib/python3.4/site-packages/pip/req/req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/its/venv/lib/python3.4/site-packages/pip/req/req_set.py", line 511, in _prepare_file
    finder, self.upgrade, require_hashes)
  File "/home/its/venv/lib/python3.4/site-packages/pip/req/req_install.py", line 277, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/its/venv/lib/python3.4/site-packages/pip/index.py", line 485, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for django-fias==0.6.1

```
проблема в том что на этой странице https://pypi.python.org/simple/django-fias/ нет версии 0.6.1

пришлось ставить напрямую с гита `pip install https://github.com/Yuego/django-fias/archive/0.6.1.tar.gz`

**Comment by Yuego** [comment]
С pip творятся какие-то непонятные вещи, недоступные моему пониманию. 
Он не даёт перезаливать релизы. 
В общем, чтоб обойти это безобразие, пришлось сменить номер версии на 0.5.9.
