### ISSUE TITLE
Проблема при установке в ActivePython 3.4 (Win64)

### ISSUE THREAD

**Issue by eldhenn** [Yuego/django-fias#50]
```
Running setup.py egg_info for package django-fias
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "django-fias\setup.py", line 30, in <module>
        long_description=open('README.rst').read(),
      File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 71: character maps to <undefined>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "django-fias\setup.py", line 30, in <module>

    long_description=open('README.rst').read(),

  File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode

    return codecs.charmap_decode(input,self.errors,decoding_table)[0]

UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 71: character maps to <undefined>
```
Скачал zip отсюда, удалил всё из README.rst, тогда пакет встал.

**Comment by Yuego** [comment]
Проблема уже не актуальна.
