### ISSUE TITLE
Не работает с Django 1.9/1.8

### ISSUE THREAD

**Issue by shamanis** [Yuego/django-fias#51]
К сожалению библиотека не работает с Django 1.9

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/models/__init__.py", line 6, in <module>
    from .normdoc import NormDoc
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/models/normdoc.py", line 6, in <module>
    from fias.fields import UUIDField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/fias/forms.py", line 6, in <module>
    from django_select2.fields import HeavyModelSelect2ChoiceField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/fields.py", line 87, in <module>
    from .widgets import Select2Widget, Select2MultipleWidget,\
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/widgets.py", line 13, in <module>
    from django.utils.datastructures import MultiValueDict, MergeDict
ImportError: cannot import name 'MergeDict'
```

MergeDict был [удален](https://docs.djangoproject.com/es/1.9/internals/deprecation/) в 1.9

Версия 0.5.1, т.к. 0.6.1 у вас висит в альфе и pip ее не хочет ставить.

**UPD:**
Поставил тег 0.6.1 через Git:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/shaman/Work/envs/smart_house/src/django-fias/fias/models/__init__.py", line 6, in <module>
    from .normdoc import NormDoc
  File "/home/shaman/Work/envs/smart_house/src/django-fias/fias/models/normdoc.py", line 6, in <module>
    from fias.fields import UUIDField
  File "/home/shaman/Work/envs/smart_house/src/django-fias/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/home/shaman/Work/envs/smart_house/src/django-fias/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/home/shaman/Work/envs/smart_house/src/django-fias/fias/forms.py", line 6, in <module>
    from django_select2.fields import HeavyModelSelect2ChoiceField
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/fields.py", line 87, in <module>
    from .widgets import Select2Widget, Select2MultipleWidget,\
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/widgets.py", line 7, in <module>
    from . import util
  File "/home/shaman/Work/envs/smart_house/lib/python3.4/site-packages/django_select2/util.py", line 195, in <module>
    from . import __ENABLE_MULTI_PROCESS_SUPPORT as ENABLE_MULTI_PROCESS_SUPPORT, \
ImportError: cannot import name '__ENABLE_MULTI_PROCESS_SUPPORT'
```

**Comment by shamanis** [comment]
По поводу последнего это проблема django-select2, [отписался](https://github.com/applegrew/django-select2/issues/271) им в git.

**Comment by shamanis** [comment]
Ради теста сменил версию python на 2.7 и получил следующее при попытке миграции:
```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/fias/models/__init__.py", line 6, in <module>
    from .normdoc import NormDoc
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/fias/models/normdoc.py", line 6, in <module>
    from fias.fields import UUIDField
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/fias/fields/__init__.py", line 5, in <module>
    from .address import AddressField, ChainedAreaField
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/fias/fields/address.py", line 11, in <module>
    from fias import forms
  File "/home/shaman/Work/envs/sh/local/lib/python2.7/site-packages/fias/forms.py", line 6, in <module>
    from django_select2.fields import HeavyModelSelect2ChoiceField
ImportError: No module named fields
```

**Comment by Yuego** [comment]
С 1.8 / 1.9 работает 1.x
