### ISSUE TITLE
Ошибка AttributeError: 'NoneType' object has no attribute '_meta'

### ISSUE THREAD

**Issue by rsashka** [Yuego/django-fias#60]
Пытаюсь импортировать базу, но вылетает следующая ошибка:
...
  File "... /env/local/lib/python2.7/site-packages/fias/importer/table/__init__.py", line 35, in parse
    return cls(filename=filename, **m.groupdict())
  File "... /env/local/lib/python2.7/site-packages/fias/importer/table/dbf.py", line 26, in __init__
    (f.name, f.rel.to) for f in self.model._meta.get_fields()
AttributeError: 'NoneType' object has no attribute '_meta'

В чем может быть ошибка? В версии django (пробовал на 1.9 и на 1.10) или из-за версии Python (пробовал на 2.7 и на 3.5)

**Comment by Yuego** [comment]
Я попробую выяснить, но нужно больше данных.

Импортируете DBF? Какая версия архива? Полный или обновление? Приложите пожалуйста полный лог импорта (вместе с выполняемой командой python manage.py fias....)

**Comment by rsashka** [comment]
Архив полный от 27 августа.

(env) alex@notebook:~/SOURCE/Django/odn/odn$ python manage.py fias --src ~/Downloads/КЛАДР/fias_dbf/
/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/suggest/backends/noop/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^suggest-area.json$', EmptyResponseListView.as_view(), name='suggest-area'),

/home/alex/SOURCE/Django/odn/odn/magic/urls.py:30: RemovedInDjango110Warning: Support for string view arguments to url() is deprecated and will be removed in Django 1.10 (got django.views.static.serve). Pass the callable instead.
  {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/management/commands/fias.py:78: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if src and src.lower() == 'auto':

Version info updated at 2016-09-18 22:27:31.972467+00:00. Estimated time: 0:00:03.520714
Loading data v.287 started at 2016-09-18 22:27:31.998414+00:00
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/management/commands/fias.py", line 133, in handle
    tempdir=tempdir,
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/importer/commands.py", line 64, in load_complete_data
    if tbl not in tablelist.tables:
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/importer/source/tablelist.py", line 49, in tables
    table = TableFactory.parse(filename=filename)
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/importer/table/__init__.py", line 35, in parse
    return cls(filename=filename, **m.groupdict())
  File "/home/alex/SOURCE/Django/odn/env/local/lib/python2.7/site-packages/fias/importer/table/dbf.py", line 26, in __init__
    (f.name, f.rel.to) for f in self.model._meta.get_fields()
AttributeError: 'NoneType' object has no attribute '_meta'

**Comment by Yuego** [comment]
Обновите версию.

**Comment by rsashka** [comment]
Импорт пошел, теперь жду, когда база загрузится  ;-)
Большое спасибо за оперативность!

**Comment by azwork13** [comment]
Добрый день день, аналогичная ошибка:
`python manage.py fias --src /home/az/Projects/fias_env/bin/test_project/fias_dbf
Version info updated at 2017-05-18 12:02:49.997035+00:00. Estimated time: 0:00:02.653448
Loading data v.353 started at 2017-05-18 12:02:50.006471+00:00
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/fias/management/commands/fias.py", line 178, in handle
    tempdir=tempdir,
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/fias/importer/commands.py", line 64, in load_complete_data
    if tbl not in tablelist.tables:
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/fias/importer/source/tablelist.py", line 49, in tables
    table = TableFactory.parse(filename=filename)
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/fias/importer/table/__init__.py", line 35, in parse
    return cls(filename=filename, **m.groupdict())
  File "/home/az/Projects/fias_env/lib/python3.5/site-packages/fias/importer/table/dbf.py", line 26, in __init__
    (f.name, f.rel.to) for f in self.model._meta.get_fields()
AttributeError: 'NoneType' object has no attribute '_meta'
`
БД ФИАС от 15.05.2017 .dbf

**Comment by azwork13** [comment]
Вопрос снимается в версии БД ФИАС от 15.05.2017 .dbf отсуствует файл addrobj, скачал другой архив - загрузка пошла, спасибо за приложение!

**Comment by Barolina** [comment]
Скажите а  можно  - узнать какой  архив   содержал  файл addrobj,  у меня такая же ошибка, качала архив 24,07,2017 ?
