### ISSUE TITLE
Ошибка при первичном импорте в версии 1.1.7

### ISSUE THREAD

**Issue by Sky-Cat** [Yuego/django-fias#62]
Команда
`python manage.py migrate`
проходит нормально.

А вот команда импорта
`python manage.py fias --src auto --format dbf --tempdir /var/foto/ --keep-indexes`
выдает ошибку. Пробовал различные комбинации параметров, xml или dbf, удаление индексов и нет.

Импорт использует фильтр, обсуждавшийся здесь: #58.

Лог ошибки:
```
python manage.py fias --src auto --format dbf --tempdir /var/foto/ --keep-indexes
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 195, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 39, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/fias/management/commands/fias.py", line 75
    def handle(self, *args, **options):
      ^
IndentationError: expected an indented block
```

В версии 1.1.2 импорт запускался.

**Comment by Yuego** [comment]
Очень странная ошибка. Я не смог её повторить у себя ни на python 2.7, ни на 3.4

Попробуйте переустановить fias, возможно, файл оказался поврежден.

Ну и если не сложно, выложите на pastebin проблемный файл. Например так:

`wgetpaste /usr/local/lib/python2.7/dist-packages/fias/management/commands/fias.py`

**Comment by Sky-Cat** [comment]
К сожалению, переустановка пакета через pip не помогла.

Файл: http://paste.debian.net/851662/

Список установленных пакетов:
```
pip list
chardet (2.3.0)
cryptography (1.5)
dbfread (2.0.6)
Django (1.9.10)
django-appconf (1.0.2)
django-extensions (1.7.2)
django-fias (1.1.7)
Django-Select2 (5.8.9)
django-tagging (0.4.3)
enum34 (1.1.6)
httplib2 (0.9.1)
idna (2.1)
ipaddress (1.0.16)
lxml (3.6.4)
mercurial (3.9.1)
mysqlclient (1.3.7)
ordereddict (1.1)
oursql (0.9.3.1)
Pillow (3.3.1)
pip (8.1.2)
progress (1.2)
pyasn1 (0.1.9)
pycurl (7.43.0)
pyOpenSSL (16.1.0)
Pyste (0.9.10)
python-apt (1.1.0b5)
python-debian (0.1.29)
python-debianbts (2.6.1)
pytz (2015.7)
rarfile (2.8)
reportbug (6.6.6)
setuptools (27.1.2)
six (1.10.0)
South (1.0.2)
sphinxit (0.3.2, /root/download/src/sphinxit)
sqlparse (0.1.18)
suds (0.4)
unrar (0.3)
virtualenv (15.0.3)
wheel (0.29.0)
```

**Comment by Yuego** [comment]
Спасибо за файл, теперь ясно, в чем проблема.

Просто обновитесь.

**Comment by Sky-Cat** [comment]
Спасибо, импорт заработал.
