### ISSUE TITLE
Ошибка при первоначальном импорте данных при наличие прокси-сервера в Интернет

### ISSUE THREAD

**Issue by Adium74** [Yuego/django-fias#72]
После установки модуля и попытке выполнить импорт данных из скачанного файла fias_xml.rar выдается ошибка

(env) root@ipam:/var/www/django/ipam# python manage.py fias --src /var/www/django/ipam/fias_xml.rar
Traceback (most recent call last):
  File "/usr/lib/python3.4/urllib/request.py", line 1174, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.4/http/client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.4/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.4/http/client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.4/http/client.py", line 924, in _send_output
    self.send(msg)
  File "/usr/lib/python3.4/http/client.py", line 859, in send
    self.connect()
  File "/usr/lib/python3.4/http/client.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/management/commands/fias.py", line 154, in handle
    fetch_version_info(update_all=True)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/version.py", line 50, in fetch_version_info
    client = Client(url=wsdl_source)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/reader.py", line 92, in download
    fp = self.options.transport.open(Request(url))
  File "/var/www/django/env/lib/python3.4/site-packages/suds/transport/https.py", line 62, in open
    return HttpTransport.open(self, request)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/transport/http.py", line 67, in open
    return self.u2open(u2request)
  File "/var/www/django/env/lib/python3.4/site-packages/suds/transport/http.py", line 132, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/lib/python3.4/urllib/request.py", line 473, in _open
    '_open', req)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 1202, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib/python3.4/urllib/request.py", line 1176, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>

Сервер с Django находится за прокси Squid, в системе заданы переменные окружения http_proxy и https_proxy.

Список установленных пакетов
(env) root@ipam:/var/www/django/ipam# pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
dbfread (2.0.7)
Django (1.10.5)
django-annoying (0.10.3)
django-appconf (1.0.2)
django-bootstrap3 (8.0.0)
django-fias (1.2.0)
django-netfields (0.7)
Django-Select2 (5.8.10)
gunicorn (19.6.0)
lxml (3.7.2)
netaddr (0.7.18)
pip (9.0.1)
progress (1.2)
psycopg2 (2.6.2)
rarfile (3.0)
setuptools (32.3.1)
six (1.10.0)
suds-jurko (0.6)
unrar (0.3)
wheel (0.29.0)

**Comment by Yuego** [comment]
SUDS не умеет работать с прокси из переменных окружения. Я кое-что подправил, но проверить нет возможности и времени настроить/найти прокси для этого. 
Так что проверку оставляю на Вас ;)
Ну и ещё можно вместо suds использовать zeep - с ним такой проблемы возникать не должно, да и вообще он предпочтительнее.
Попробуйте и отпишитесь о результатах пожалуйста.

**Comment by Adium74** [comment]
Установил zeep, теперь другая ошибка
`(env) root@ipam:/var/www/django/ipam# python manage.py fias --src /var/www/django/ipam/fias_xml.rar
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/management/commands/fias.py", line 154, in handle
    fetch_version_info(update_all=True)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/version.py", line 20, in fetch_version_info
    for item in result.DownloadFileInfo:
AttributeError: 'list' object has no attribute 'DownloadFileInfo'
`

**Comment by Yuego** [comment]
zeep-0.20+ изменил API. Поддержку я добавил совсем недавно.
Обновите версию fias. Заодно попробуйте удалить zeep и проверить работу suds через прокси.

**Comment by Adium74** [comment]
Обновил fias. Удалил zeep. Попробовал сделать загрузку

(env) root@ipam:/var/www/django/ipam# python manage.py fias --src /var/www/django/ipam/fias_xml.rar --truncate --i-know-what-i-do
/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)

Version info updated at 2017-01-10 06:15:21.094887+00:00. Estimated time: 0:00:01.976725
Loading data v.312 started at 2017-01-10 06:15:21.132568+00:00
T: actstat. L: 2 | U: 0 | S: 1[E:0] | R: 0[0]   FN: AS_ACTSTAT_20161130_4ac81cdd-c52c-4004-8889-8bb75d552209.XML
T: centerst. L: 5 | U: 0 | S: 1[E:0] | R: 0[0]  FN: AS_CENTERST_20161130_55b82d0d-1317-450c-b50b-2a5cb0db2c80.XML
T: curentst. L: 100 | U: 0 | S: 1[E:0] | R: 0[0]        FN: AS_CURENTST_20161130_b393a295-0a71-4185-856e-90e971501d46.XML
T: eststat. L: 5 | U: 0 | S: 1[E:0] | R: 0[0]   FN: AS_ESTSTAT_20161130_7fe4ce7a-a545-405c-bc9a-dad3689a4e3d.XML
T: hststat. L: 43 | U: 0 | S: 1[E:0] | R: 0[0]  FN: AS_HSTSTAT_20161130_ed81a1e9-8d80-4e25-87c3-340cb685ac66.XML
T: intvstat. L: 4 | U: 0 | S: 1[E:0] | R: 0[0]  FN: AS_INTVSTAT_20161130_d2ce9a56-5701-417a-a359-8c3fae92126d.XML
T: ndoctype. L: 26 | U: 0 | S: 1[E:0] | R: 0[0]         FN: AS_NDOCTYPE_20161130_d9a4cdc9-6cfa-438c-a32b-9b41c914a7e0.XML
T: operstat. L: 17 | U: 0 | S: 1[E:0] | R: 0[0]         FN: AS_OPERSTAT_20161130_516a5d32-7d3f-42f7-b9fb-8ba68e1c2f33.XML
T: strstat. L: 4 | U: 0 | S: 1[E:0] | R: 0[0]   FN: AS_STRSTAT_20161130_a7d56839-58a0-4328-9c41-c1229e344b2e.XML
T: socrbase. L: 390 | U: 0 | S: 2[E:0] | R: 0[0]        FN: AS_SOCRBASE_20161130_7caf0640-5625-4a5c-9814-a52fd7a4346c.XML
T: addrobj. L: 0 | U: 0 | S: 10000[E:0] | R: 0[0]       FN: AS_ADDROBJ_20161130_7178572f-4d02-4645-bd39-c6b2c71590fe.XMLTraceback (most recent call last):
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/commands.py", line 68, in load_complete_data
    st = Status.objects.get(table=tbl)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/query.py", line 387, in get
    self.model._meta.object_name
fias.models.version.DoesNotExist: Status matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column "plancode" of relation "fias_addrobj" does not exist
LINE 1: ... "areacode", "citycode", "ctarcode", "placecode", "plancode"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/www/django/env/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/management/commands/fias.py", line 178, in handle
    tempdir=tempdir,
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/commands.py", line 89, in load_complete_data
    loader.load(tablelist=tablelist, table=table)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/loader.py", line 127, in load
    self.do_load(tablelist=tablelist, table=table)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/loader.py", line 147, in do_load
    self.create(table, objects, bar=bar)
  File "/var/www/django/env/lib/python3.4/site-packages/fias/importer/loader.py", line 116, in create
    table.model.objects.bulk_create(objects)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/query.py", line 447, in bulk_create
    self._batched_insert(objs_with_pk, fields, batch_size)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/query.py", line 1056, in _batched_insert
    using=self.db)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/query.py", line 1039, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/django/env/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/var/www/django/env/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column "plancode" of relation "fias_addrobj" does not exist
LINE 1: ... "areacode", "citycode", "ctarcode", "placecode", "plancode"...
                                                             ^

Есть столбец plaincode.

**Comment by Yuego** [comment]
Вы установили приложение с нуля или обновили существующую версию?
Если второе - обновите схему БД.

 Обратите внимание:
https://github.com/Yuego/django-fias#%D0%9E%D0%B1%D0%BD%D0%BE%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5-11x-%D0%B4%D0%BE-120

Ошибка же была исправлена ещё в #70

`python manage.py migrate`

или, если отдельная БД

`python manage.py migrate --database fias`

**Comment by Adium74** [comment]
Обновлял уже установленное. После миграции все успешно импортировалось.
Loading data v.312 started at 2017-01-10 09:16:32.205876+00:00
...
Data v.312 from 2016-11-28 loaded at 2017-01-10 10:15:36.164157+00:00
Estimated time: 0:59:05.808548. Download: 0. Unpack: 0. Import: 0:59:03.962631

P.S.: если django 1.10 поддерживается, то в зависимостях поправьте, а то при обновлении модуля fias сносится django 1.10 и ставится 1.9

**Comment by Yuego** [comment]
Основные тесты с 1.10 проходят и работать должно, но на 100% я не уверен (покрытие тестами очень слабое). Думаю, проблем ожидать не стоит, а потому, я добавил новую версию. Обновитесь.
