### ISSUE TITLE
render_options() missing 1 required positional argument: 'selected_choices'

### ISSUE THREAD

**Issue by lcd1232** [Yuego/django-fias#74]
url - http://localhost:8000/admin/tst/item/add/
python version - 3.5.2
libraries
```
appdirs==1.4.3
cached-property==1.3.0
dbfread==2.0.7
defusedxml==0.5.0
Django==1.10.6
django-appconf==1.0.2
Django-Select2==5.8.10
isodate==0.5.4
lxml==3.7.3
mysqlclient==1.3.10
packaging==16.8
progress==1.2
pyparsing==2.2.0
pytz==2016.10
rarfile==3.0
requests==2.13.0
requests-toolbelt==0.7.1
six==1.10.0
unrar==0.3
zeep==1.1.0
```
Проблема происходит в тестовом проекте, который находится в репозитории.
<details><summary>Stacktrace:(Click to expand)</summary><p>

```

Environment:


Request Method: GET
Request URL: http://localhost:8000/admin/tst/item/add/

Django Version: 1.10.6
Python Version: 3.5.2
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admin',
 'django.contrib.admindocs',
 'fias',
 'django_select2',
 'tst')
Installed Middleware:
('django.middleware.common.CommonMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware')


Template error:
In template /home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/contrib/admin/templates/admin/change_form.html, error at line 33
   render_options() missing 1 required positional argument: 'selected_choices'   23 : {% endblock %}
   24 : {% endif %}
   25 : 
   26 : {% block content %}<div id="content-main">
   27 : {% block object-tools %}
   28 : {% if change %}{% if not is_popup %}
   29 :   <ul class="object-tools">
   30 :     {% block object-tools-items %}
   31 :     <li>
   32 :         {% url opts|admin_urlname:'history' original.pk|admin_urlquote as history_url %}
   33 :         <a href=" {% add_preserved_ filters history_url %}" class="historylink">{% trans "History" %}</a>
   34 :     </li>
   35 :     {% if has_absolute_url %}<li><a href="{{ absolute_url }}" class="viewsitelink">{% trans "View on site" %}</a></li>{% endif %}
   36 :     {% endblock %}
   37 :   </ul>
   38 : {% endif %}{% endif %}
   39 : {% endblock %}
   40 : <form {% if has_file_field %}enctype="multipart/form-data" {% endif %}action="{{ form_url }}" method="post" id="{{ opts.model_name }}_form" novalidate>{% csrf_token %}{% block form_top %}{% endblock %}
   41 : <div>
   42 : {% if is_popup %}<input type="hidden" name="{{ is_popup_var }}" value="1" />{% endif %}
   43 : {% if to_field %}<input type="hidden" name="{{ to_field_var }}" value="{{ to_field }}" />{% endif %}


Traceback:

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  42.             response = get_response(request)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  217.                 response = self.process_exception_by_middleware(e, request)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  215.                 response = response.render()

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/response.py" in render
  109.             self.content = self.rendered_content

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/response.py" in rendered_content
  86.         content = template.render(context, self._request)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/backends/django.py" in render
  66.             return self.template.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  208.                     return self._render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  174.         return compiled_parent._render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  174.         return compiled_parent._render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  70.                 result = block.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  70.                 result = block.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/loader_tags.py" in render
  210.                 return template.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  210.                 return self._render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in _render
  199.         return self.nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  209.                     nodelist.append(node.render_annotated(context))

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  315.                 return nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/defaulttags.py" in render
  315.                 return nodelist.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  994.                 bit = node.render_annotated(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_annotated
  961.             return self.render(context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render
  1050.         return render_value_in_context(output, context)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/template/base.py" in render_value_in_context
  1028.     value = force_text(value)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/utils/encoding.py" in force_text
  76.                     s = six.text_type(s)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/utils/html.py" in <lambda>
  391.         klass.__str__ = lambda self: mark_safe(klass_str(self))

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/forms/boundfield.py" in __str__
  43.         return self.as_widget()

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/forms/boundfield.py" in as_widget
  101.         return force_text(widget.render(name, self.value(), attrs=attrs))

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/contrib/admin/widgets.py" in render
  307.             'widget': self.widget.render(name, value, *args, **kwargs),

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django_select2/forms.py" in render
  218.         output = super(HeavySelect2Mixin, self).render(*args, **kwargs)

File "/home/mikhail/.virtualenvs/fias/lib/python3.5/site-packages/django/forms/widgets.py" in render
  550.         options = self.render_options([value])

Exception Type: TypeError at /admin/tst/item/add/
Exception Value: render_options() missing 1 required positional argument: 'selected_choices'

```

</p></details>

#### UPDATE.
В файле fias/forms.py заменил строку 24
`def render_options(self, choices, selected_choices):`
на эту
`def render_options(self, selected_choices):`
и ошибка исчезла.

**Comment by RomanKovalev** [comment]
При установке из PyPi (pip install django-fias) устанавливается старая версия fias/forms.py (в которую не внесены данные из коммита (https://github.com/Yuego/django-fias/commit/170a8afc99554c2d59b43184385c516b9e006003) 
Когда заменяю fias/forms.py на актуальный, то всё также не работает.
``System check identified no issues (0 silenced).
August 02, 2018 - 11:57:21
Django version 1.10.8, using settings 'fiasapi.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
Internal Server Error: /admin/api/item/add/
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 217, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 215, in _get_response
    response = response.render()
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 109, in render
    self.content = self.rendered_content
  File "/usr/local/lib/python3.7/site-packages/django/template/response.py", line 86, in rendered_content
    content = template.render(context, self._request)
  File "/usr/local/lib/python3.7/site-packages/django/template/backends/django.py", line 66, in render
    return self.template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 208, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 174, in render
    return compiled_parent._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 70, in render
    result = block.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/loader_tags.py", line 210, in render
    return template.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 199, in _render
    return self.nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 994, in render
    bit = node.render_annotated(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 1050, in render
    return render_value_in_context(output, context)
  File "/usr/local/lib/python3.7/site-packages/django/template/base.py", line 1028, in render_value_in_context
    value = force_text(value)
  File "/usr/local/lib/python3.7/site-packages/django/utils/encoding.py", line 76, in force_text
    s = six.text_type(s)
  File "/usr/local/lib/python3.7/site-packages/django/utils/html.py", line 391, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 43, in __str__
    return self.as_widget()
  File "/usr/local/lib/python3.7/site-packages/django/forms/boundfield.py", line 101, in as_widget
    return force_text(widget.render(name, self.value(), attrs=attrs))
  File "/usr/local/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 307, in render
    'widget': self.widget.render(name, value, *args, **kwargs),
  File "/usr/local/lib/python3.7/site-packages/django_select2/forms.py", line 258, in render
    output = super(HeavySelect2Mixin, self).render(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/forms/widgets.py", line 550, in render
    options = self.render_options([value])
  File "/usr/local/lib/python3.7/site-packages/fias/forms.py", line 36, in render_options
    return super(AddressSelect2Widget, self).render_options(choices, selected_choices)
TypeError: render_options() takes 2 positional arguments but 3 were given
[02/Aug/2018 11:57:25] "GET /admin/api/item/add/ HTTP/1.1" 500 541993
Performing system checks...
``
