### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_meta'

### ISSUE THREAD

**Issue by Barolina** [Yuego/django-fias#78]
Подскажите :(((  ошибка , 
 File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\fias\management\commands\fias.py", line 178, in handle
    tempdir=tempdir,
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\fias\importer\commands.py", line 64, in load_complete_data
    if tbl not in tablelist.tables:
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\fias\importer\source\tablelist.py", line 49, in tables
    table = TableFactory.parse(filename=filename)
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\fias\importer\table\__init__.py", line 35, in parse
    return cls(filename=filename, **m.groupdict())
  File "D:\projects\pr_fias\venv-pr\lib\site-packages\fias\importer\table\dbf.py", line 26, in __init__
    (f.name, f.rel.to) for f in self.model._meta.get_fields()
AttributeError: 'NoneType' object has no attribute '_meta'

Архив скачала 24.07.2017
Django 1.10.7
python 3.5

**Comment by butschster** [comment]
Попробуй распаковать архив и указать директорию с файлами для импорта

**Comment by ericovva** [comment]
не помогло

**Comment by ericovva** [comment]
`$ python manage.py fias --src fias_xml/
Version info updated at 2017-11-08 12:43:55.206027+00:00. Estimated time: 0:00:00.478571
Loading data v.397 started at 2017-11-08 12:43:55.221624+00:00
Traceback (most recent call last):
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/commands.py", line 68, in load_complete_data
    st = Status.objects.get(table=tbl)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
fias.models.version.DoesNotExist: Status matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/management/commands/fias.py", line 178, in handle
    tempdir=tempdir,
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/commands.py", line 83, in load_complete_data
    remove_indexes_from_model(model=first_table.model)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/indexes.py", line 60, in remove_indexes_from_model
    change_indexes_for_model(model=model, field_from=field, field_to=simple_field)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/indexes.py", line 55, in change_indexes_for_model
    ed.alter_field(model, field_from, field_to)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 255, in _alter_field
    self._remake_table(model, alter_fields=[(old_field, new_field)])
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 172, in _remake_table
    temp_model = type(model._meta.object_name, model.__bases__, body)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._prepare()
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/base.py", line 343, in _prepare
    cls.__doc__ = "%s(%s)" % (cls.__name__, ", ".join(f.name for f in opts.fields))
TypeError: sequence item 2: expected str instance, NoneType found
`

**Comment by ericovva** [comment]
такая ошибка, если указывать распакованную директорию

**Comment by buzzySmile** [comment]
@ericovva У вас другого рода ошибка, лучше заведите отдельный issue.
В этом issue проблема была с импортом из dbf, и к слову корректировка, предложенная @butschster'ом, не всегда помогает, ибо архивы обновлений могут содержать внезапные ошибки. 
Пробуйте разные версии и форматы баз, если ничего не помогает.

**Comment by ericovva** [comment]
Проблему решил поменяв версию бд

**Comment by ericovva** [comment]
А с dbf проблема в том, что новые архивы разбиваются для каждой таблица на 100 dbf файлов, а этот импорт, как я понял, рассчитан на иморт из одного большого файла
