### ISSUE TITLE
TypeError: sequence item 2: expected str instance, NoneType found

### ISSUE THREAD

**Issue by ericovva** [Yuego/django-fias#83]
$ python manage.py fias --src fias_xml/
Version info updated at 2017-11-09 14:25:28.121517+00:00. Estimated time: 0:00:00.356406
Loading data v.397 started at 2017-11-09 14:25:28.130648+00:00
Traceback (most recent call last):
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/commands.py", line 68, in load_complete_data
    st = Status.objects.get(table=tbl)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
fias.models.version.DoesNotExist: Status matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/management/commands/fias.py", line 178, in handle
    tempdir=tempdir,
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/commands.py", line 83, in load_complete_data
    remove_indexes_from_model(model=first_table.model)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/indexes.py", line 60, in remove_indexes_from_model
    change_indexes_for_model(model=model, field_from=field, field_to=simple_field)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/fias/importer/indexes.py", line 55, in change_indexes_for_model
    ed.alter_field(model, field_from, field_to)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 255, in _alter_field
    self._remake_table(model, alter_fields=[(old_field, new_field)])
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 172, in _remake_table
    temp_model = type(model._meta.object_name, model.__bases__, body)
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/base.py", line 309, in __new__
    new_class._prepare()
  File "/Users/e.ovsepyan/.virtualenvs/ganesha_fias3/lib/python3.6/site-packages/django/db/models/base.py", line 343, in _prepare
    cls.__doc__ = "%s(%s)" % (cls.__name__, ", ".join(f.name for f in opts.fields))
TypeError: sequence item 2: expected str instance, NoneType found

**Comment by ericovva** [comment]
Также возникает при импорте fias_dbf, зависит от версии архива

**Comment by ericovva** [comment]
база была не psql, мой косяк
