### ISSUE TITLE
django.core.exceptions.FieldError

### ISSUE THREAD

**Issue by Khovanskiy5** [Yuego/django-fias#94]
(fiasenv) khovanskiy@ubuntu-server:~/fias/fiasenv/django-fias/test_project$ python manage.py fias --src ../../../fias_xml.rar --i-know-what-i-do --truncate
Version info updated at 2019-04-26 13:58:39.800450+00:00. Estimated time: 0:00:04.273767
Loading data v.538 started at 2019-04-26 13:58:39.815834+00:00
Traceback (most recent call last):
  File "/home/khovanskiy/fias/fiasenv/django-fias/test_project/fias/importer/commands.py", line 68, in load_complete_data
    st = Status.objects.get(table=tbl)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/models/query.py", line 334, in get
    self.model._meta.object_name
fias.models.version.DoesNotExist: Status matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/khovanskiy/fias/fiasenv/django-fias/test_project/fias/management/commands/fias.py", line 178, in handle
    tempdir=tempdir,
  File "/home/khovanskiy/fias/fiasenv/django-fias/test_project/fias/importer/commands.py", line 83, in load_complete_data
    remove_indexes_from_model(model=first_table.model)
  File "/home/khovanskiy/fias/fiasenv/django-fias/test_project/fias/importer/indexes.py", line 65, in remove_indexes_from_model
    change_indexes_for_model(model=model, field_from=field, field_to=simple_field)
  File "/home/khovanskiy/fias/fiasenv/django-fias/test_project/fias/importer/indexes.py", line 58, in change_indexes_for_model
    ed.alter_field(model, field_from, field_to)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/backends/base/schema.py", line 484, in alter_field
    old_db_params, new_db_params, strict)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 200, in _alter_field
    self._remake_table(model, alter_fields=[(old_field, new_field)])
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/backends/sqlite3/schema.py", line 133, in _remake_table
    temp_model = type(model._meta.object_name, model.__bases__, body)
  File "/home/khovanskiy/fias/fiasenv/lib/python3.6/site-packages/django/db/models/base.py", line 254, in __new__
    'base class %r' % (field.name, name, base.__name__)
django.core.exceptions.FieldError: Local field 'name' in class 'FlatType' clashes with field of similar name from base class 'AbstractType'

(fiasenv) khovanskiy@ubuntu-server:~/fias/fiasenv/django-fias/test_project$ pip list
Package           Version
----------------- --------
appdirs           1.4.3
attrs             19.1.0
cached-property   1.5.1
certifi           2019.3.9
chardet           3.0.4
dbfread           2.0.7
defusedxml        0.6.0
Django            1.8
django-appconf    1.0.3
django-extensions 2.1.6
django-fias       1.2.5
Django-Select2    5.3.0
idna              2.8
isodate           0.6.0
lxml              4.3.3
pip               19.1
progress          1.5
pytz              2019.1
rarfile           3.0
requests          2.21.0
requests-toolbelt 0.9.1
setuptools        41.0.1
six               1.12.0
unrar             0.3
urllib3           1.24.2
wheel             0.33.1

(fiasenv) khovanskiy@ubuntu-server:~/fias/fiasenv/django-fias/test_project$ uname -a
Linux ubuntu-server 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux 18.04 LTS

(fiasenv) khovanskiy@ubuntu-server:~/fias/fiasenv/django-fias/test_project$ python --version
Python 3.6.7

разворачивал test_project

**Comment by LennyLip** [comment]
Такая жеп фигня была, добавил strstat по-моему. Или еще что-то, не помню, сравните таблицу 
fias.fias_status;

![strstat](https://user-images.githubusercontent.com/955994/58004556-2994d100-7aec-11e9-9534-0c89fcfa0a72.png)

**Comment by Khovanskiy5** [comment]
@LennyLip Спасибо, поковыряю отпишу...
